## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
clean_application_df = application_df.drop(['EIN', 'NAME'], axis=1)
clean_application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [6]:
# Determine the number of unique values in each column.
unique_values= clean_application_df.nunique()
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
app_type= clean_application_df['APPLICATION_TYPE'].value_counts()
app_type

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff= 500
application_types_to_replace= list(app_type[app_type<cutoff].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
class_type= clean_application_df['CLASSIFICATION'].value_counts()
class_type

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_type1= class_type[class_type >1]
class_type1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_cutoff= 1000
class_type= clean_application_df['CLASSIFICATION'].value_counts()
classifications_to_replace= list(class_type[class_type<class_cutoff].index)


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
cat_app_df= pd.get_dummies(clean_application_df)
cat_app_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [14]:
# Split our preprocessed data into our features and target arrays
X= cat_app_df.drop("IS_SUCCESSFUL", axis=1).values
y= cat_app_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=10)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [19]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=100, activation='relu', input_dim=116))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=100, activation='relu'))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn_model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 100)            │        11,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,901 (85.55 KB)

 Trainable params: 21,901 (85.55 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics= ["accuracy"])

In [25]:
# Train the model
fit_model= nn_model.fit(X_train_scaled, y_train, epochs=100, )

Epoch 1/100

804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 412us/step - accuracy: 0.7141 - loss: 0.5896
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - accuracy: 0.7328 - loss: 0.5528
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.7338 - loss: 0.5510
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - accuracy: 0.7404 - loss: 0.5416
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - accuracy: 0.7348 - loss: 0.5462
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 396us/step - accuracy: 0.7360 - loss: 0.5421
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - accuracy: 0.7370 - loss: 0.5436
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.7364 - loss: 0.5393
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7378 - loss: 0.5426
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.7381 - loss: 0.5400
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - accuracy: 0.7400 - loss: 0.5368
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - accuracy: 0.7403 - loss: 0.5378
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - accuracy: 0.7350 - loss: 0.5431
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - accuracy: 0.7433 - loss: 0.5338
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 356us/step - accuracy: 0.7391 - loss: 0.5380
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7410 - loss: 0.5354
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - accuracy: 0.7381 - loss: 0.5364
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - accuracy: 0.7377 - loss: 0.5376
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - accuracy: 0.7418 - loss: 0.5358
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - accuracy: 0.7398 - loss: 0.5365
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.7371 - loss: 0.5407
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - accuracy: 0.7402 - loss: 0.5361
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - accuracy: 0.7359 - loss: 0.5394
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.7435 - loss: 0.5353
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - accuracy: 0.7423 - loss: 0.5315
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - accuracy: 0.7441 - loss: 0.5318
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7445 - loss: 0.5332
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 398us/step - accuracy: 0.7439 - loss: 0.5327
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7410 - loss: 0.5352
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - accuracy: 0.7348 - loss: 0.5392
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 368us/step - accuracy: 0.7422 - loss: 0.5318
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - accuracy: 0.7447 - loss: 0.5317
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - accuracy: 0.7395 - loss: 0.5346
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.7423 - loss: 0.5305
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7400 - loss: 0.5319
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.7467 - loss: 0.5271
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.7457 - loss: 0.5287
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - accuracy: 0.7356 - loss: 0.5384
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.7445 - loss: 0.5284
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - accuracy: 0.7459 - loss: 0.5264
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.7486 - loss: 0.5245
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - accuracy: 0.7413 - loss: 0.5294
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - accuracy: 0.7450 - loss: 0.5311
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - accuracy: 0.7480 - loss: 0.5276
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7427 - loss: 0.5325
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - accuracy: 0.7466 - loss: 0.5245
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7441 - loss: 0.5279
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.7445 - loss: 0.5260
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - accuracy: 0.7413 - loss: 0.5319
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - accuracy: 0.7442 - loss: 0.5277
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.7438 - loss: 0.5283
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - accuracy: 0.7454 - loss: 0.5279
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - accuracy: 0.7411 - loss: 0.5305
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - accuracy: 0.7427 - loss: 0.5295
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - accuracy: 0.7475 - loss: 0.5277
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - accuracy: 0.7415 - loss: 0.5304
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - accuracy: 0.7486 - loss: 0.5272
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7453 - loss: 0.5273
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7489 - loss: 0.5227
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 368us/step - accuracy: 0.7428 - loss: 0.5278
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - accuracy: 0.7429 - loss: 0.5297
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - accuracy: 0.7474 - loss: 0.5252
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - accuracy: 0.7448 - loss: 0.5268
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - accuracy: 0.7424 - loss: 0.5294
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7420 - loss: 0.5293
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - accuracy: 0.7460 - loss: 0.5256
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - accuracy: 0.7492 - loss: 0.5211
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.7413 - loss: 0.5293
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - accuracy: 0.7428 - loss: 0.5283
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7429 - loss: 0.5277
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7469 - loss: 0.5266
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - accuracy: 0.7459 - loss: 0.5258
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step - accuracy: 0.7491 - loss: 0.5252
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - accuracy: 0.7429 - loss: 0.5286
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - accuracy: 0.7427 - loss: 0.5288
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - accuracy: 0.7503 - loss: 0.5218
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7384 - loss: 0.5332
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - accuracy: 0.7439 - loss: 0.5285
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7426 - loss: 0.5288
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - accuracy: 0.7450 - loss: 0.5242
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - accuracy: 0.7433 - loss: 0.5279
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - accuracy: 0.7469 - loss: 0.5256
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7436 - loss: 0.5319
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 368us/step - accuracy: 0.7429 - loss: 0.5272
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - accuracy: 0.7431 - loss: 0.5302
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - accuracy: 0.7470 - loss: 0.5255
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 388us/step - accuracy: 0.7460 - loss: 0.5265
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - accuracy: 0.7424 - loss: 0.5256
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - accuracy: 0.7421 - loss: 0.5271
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - accuracy: 0.7490 - loss: 0.5234
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7449 - loss: 0.5257
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - accuracy: 0.7501 - loss: 0.5186
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.7402 - loss: 0.5287
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - accuracy: 0.7469 - loss: 0.5265
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - accuracy: 0.7421 - loss: 0.5326
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - accuracy: 0.7453 - loss: 0.5249
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7469 - loss: 0.5245
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - accuracy: 0.7445 - loss: 0.5310
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.7465 - loss: 0.5230
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - accuracy: 0.7467 - loss: 0.5225

In [27]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 437us/step - accuracy: 0.7289 - loss: 0.6614
Loss: 0.6613861918449402, Accuracy: 0.728863000869751

In [28]:
# Export our model to HDF5 file
nn_model.save('h5Files/AlphabetSoupCharity.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.